config/routes.rb
DemoApp::Application.routes.draw do
  resources :micropsts

  resources :users

end

app/models/micropst.rb
class Micropst < ActiveRecord::Base
  validates :content, :length=> {:maximum =>140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/micropsts_controller.rb
class MicropstsController < ApplicationController
  # GET /micropsts
  # GET /micropsts.xml
  def index
    @micropsts = Micropst.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @micropsts }
    end
  end

  # GET /micropsts/1
  # GET /micropsts/1.xml
  def show
    @micropst = Micropst.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @micropst }
    end
  end

  # GET /micropsts/new
  # GET /micropsts/new.xml
  def new
    @micropst = Micropst.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @micropst }
    end
  end

  # GET /micropsts/1/edit
  def edit
    @micropst = Micropst.find(params[:id])
  end

  # POST /micropsts
  # POST /micropsts.xml
  def create
    @micropst = Micropst.new(params[:micropst])

    respond_to do |format|
      if @micropst.save
        format.html { redirect_to(@micropst, :notice => 'Micropst was successfully created.') }
        format.xml  { render :xml => @micropst, :status => :created, :location => @micropst }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @micropst.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /micropsts/1
  # PUT /micropsts/1.xml
  def update
    @micropst = Micropst.find(params[:id])

    respond_to do |format|
      if @micropst.update_attributes(params[:micropst])
        format.html { redirect_to(@micropst, :notice => 'Micropst was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @micropst.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /micropsts/1
  # DELETE /micropsts/1.xml
  def destroy
    @micropst = Micropst.find(params[:id])
    @micropst.destroy

    respond_to do |format|
      format.html { redirect_to(micropsts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micropsts_helper.rb
module MicropstsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/micropsts/_form.html.erb
<%= form_for(@micropst) do |f| %>
  <% if @micropst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropst.errors.count, "error") %> prohibited this micropst from being saved:</h2>

      <ul>
      <% @micropst.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micropsts/edit.html.erb
<h1>Editing micropst</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropst %> |
<%= link_to 'Back', micropsts_path %>

app/views/micropsts/index.html.erb
<h1>Listing micropsts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micropsts.each do |micropst| %>
  <tr>
    <td><%= micropst.content %></td>
    <td><%= micropst.user_id %></td>
    <td><%= link_to 'Show', micropst %></td>
    <td><%= link_to 'Edit', edit_micropst_path(micropst) %></td>
    <td><%= link_to 'Destroy', micropst, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropst', new_micropst_path %>

app/views/micropsts/new.html.erb
<h1>New micropst</h1>

<%= render 'form' %>

<%= link_to 'Back', micropsts_path %>

app/views/micropsts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropst.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropst.user_id %>
</p>


<%= link_to 'Edit', edit_micropst_path(@micropst) %> |
<%= link_to 'Back', micropsts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>